name: Conditional Manual Trigger

on: workflow_dispatch

jobs:
  check-previous:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.get_branch.outputs.branch_name }}
    steps:
      - name: Get branch name
        id: get_branch
        run: echo "::set-output name=branch_name::${GITHUB_REF#refs/heads/}"
      - name: Write branch name
        run: echo "${{ steps.get_branch.outputs.branch_name }}"
      - name: Check previous workflow status
        uses: actions/github-script@v7
        env:
          branch_name: ${{ steps.get_branch.outputs.branch_name }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const branchName = process.env.BRANCH_NAME;
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: "1_workflow.yml",
              branch: branchName
            });
            console.log(workflows.data.workflow_runs);
            if (!workflows.data.workflow_runs.length || workflows.data.workflow_runs[0].conclusion !== "success") {
              core.setFailed("Previous workflow did not succeed. Manual trigger denied.");
            }

  run-task:
    needs: check-previous
    runs-on: ubuntu-latest
    steps:
      - name: Execute workflow step
        run: echo "This workflow was manually triggered and the previous workflow succeeded."