name: Conditional Manual Trigger

on:
  workflow_dispatch:

jobs:
  check-previous:
    runs-on: ubuntu-latest
    steps:
      - name: Check previous workflow status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const workflows = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: "1_workflow.yml",
            });
            if (!workflows.data.workflow_runs.length || workflows.data.workflow_runs[0].conclusion !== "success") {
              core.setFailed("Previous workflow did not succeed. Manual trigger denied.");
            }

  run-task:
    needs: check-previous
    runs-on: ubuntu-latest
    steps:
      - name: Execute workflow step
        run: echo "This workflow was manually triggered and the previous workflow succeeded."